### PR TITLE
Fix HeaderCreator leaking file descriptors

### LINKED ISSUE #127: HeaderCreator leaking file descriptors
Hi, 
recently we were having serious troubles using sbt-header plugin on Windows 10 with git. Especially with enabled `AutomateHeaderPlugin`. While running SBT almost every operation with git failed (pull, revert, rebase) with odd errors about unable to unlink old file. You have to turn SBT off, then execute git operation and then turn SBT back on to continue development (which is pretty annoying).

I've located cause to the `HeaderCreator`, line `val fileContent = scala.io.Source.fromInputStream(input)(Codec.UTF8).mkString`. `Source.fromInputStream` is not closing `input`, so file descriptor is open till SBT is closed, thus preventing git and sometimes event IntelliJ IDEA to modify file. Even in case file was not modified by the user, but only check for correct header.

Simply wrapping it and close input stream will do the magic (I'm not sure why `InputStream` is passed down, instead of `Path`):
```
    val fileContent = try {
      scala.io.Source.fromInputStream(input)(Codec.UTF8).mkString
    } finally {
      input.close()
    }
```

### PR DESCRIPTION
**Pull request by krchniam**
Fixes #127 with little cleanup

### CODE REVIEW

**Comment by hseeberger** [comment]
Thanks!

Tests are failing, not even compiling. Please fix,

**Comment by britter** [comment]
@hseeberger Codacy suggests to do something with `scala.util.Try` instead of using try-catch-finally. I don't shee how `Try` can help here. Do you see a more idiomatic way to implement the try-catch part?

**Comment by krchniam** [comment]
Should compile now, missed the usage in test.

**Comment by hseeberger** [comment]
Codacy is wrong! Using Try for implementation only (not as return value) needlessly allocates and should be avoided. Good old try-catch is just fine.

**Pull request merged**
