### PR TITLE
Allow for /** C-style comments

### PR DESCRIPTION
**Pull request by derekwyatt**
- This change provides the ability to use comments that look like:
   /**
    * License is here
    */

- Other changes were made by scalariform

### CODE REVIEW

**Comment by hseeberger** [comment]
LGTM

**Comment by derekwyatt** [comment]
Keen. :)  I just prefer that style of commenting and when I used it to make my header, `sbt-header` just kept making duplicates.

**Comment by britter** [comment]
I'd recommend not changing the existing behavior but adding this as a new comment style.

**Comment by derekwyatt** [comment]
Why? I can't see an advantage

**Comment by derekwyatt** [comment]
Done.

**Comment by hseeberger** [comment]
Thanks!

**Pull request merged**
