### PR TITLE
Rename Licenses trait to License and make it an object

### PR DESCRIPTION
**Pull request by britter**
Partical fix for #93 addressing the first two tasks.

### CODE REVIEW

**Comment by britter** [comment]
@hseeberger: The third task in #93 is to make all `License` implementations objects with an `apply` method taking the year and copy right owner as parameters and returning the license text. I don't know how to implement this for the `Custom` license. Any idea?

**Comment by britter** [comment]
codacy failed because of `val HeaderLicense` in `autoImport`. Codacy wants fields to start with lower case.

**Comment by hseeberger** [comment]
Codacy should Take a Look at scala.Predef and the scala Package object ;-)

**Comment by hseeberger** [comment]
@britter I think you have to introduce `StandardLicense extends License` and add `def text(yyyy, owner)` to that instead of `License`. When pattern matching on the license you have to disambiguate btw. `Custom` and `StandardLicense`.

**Comment by britter** [comment]
@hseeberger I'm gave that a try but ran into the following problem:

```scala
sealed trait License {
  def apply(text: String) = text
}

sealed trait SpdxLicense extends License {
  val identifier: String
  val apply(yyyy: String, copyrightOwner: String)
}

final case object Custom extends License

final case object ALv2 extends SpdxLicense {
  override val identifier = "Apache-2.0"
  override def apply(yyyy: String, copyrightOwner: String)

  // what to do here? We want ALv2 to only have apply(yyyy: String, copyrightOwner: String)
  override def apply(text: String) = ???
}
```

**Comment by hseeberger** [comment]
The License trait should 't have text.

And don't use abstract vals, use defs unsträflich.

**Comment by britter** [comment]
@hseeberger how about ff25a03 ?

**Pull request merged**
