### PR TITLE
Add GNU licenses

### PR DESCRIPTION
**Pull request by britter**
As discussed in #38 and #39 here is a PR to add GPLv3 and LGPLv3.

### CODE REVIEW

**Comment by britter** [comment]
I'm not sure about the header text for LGPL, since the [license text](http://www.gnu.org/licenses/lgpl-3.0.en.html) does not include an example. I adapted it from the GPL header.

**Comment by hseeberger** [comment]
I'm indifferent wrt this topic.

**Comment by fommil** [comment]
:smile:

**Comment by fommil** [comment]
Now all we have to do is stick `@deprecated` on everything else

**Pull request merged**
