### PR TITLE
Bugfix: Use the right sbt cache API

### PR DESCRIPTION
**Pull request by johanandren**
The previous cache incantation one would throw an exception when removing a file
previosly seen and modified by the createHeader.

### CODE REVIEW

**Comment by johanandren** [comment]
@hseeberger any chance we could get a new release with this fix in?

**Comment by hseeberger** [comment]
Sure mate, stay tuned.

**Comment by hseeberger** [comment]
@johanandren 5.3.1 has been released.

**Comment by johanandren** [comment]
Excellent. Thanks!

**Pull request merged**
