### PR TITLE
Allow project-specific CommentCreator taking into account the existing header

### PR DESCRIPTION
**Pull request by raboof**
Could be used to implement #23

Just a sketch for feedback, if the general approach looks OK I'll add tests and look more closely at binary compatibility.

### CODE REVIEW

**Comment by hseeberger** [comment]
Thanks!

Sorry to ask, but what would be the exact effect of this change?

**Comment by raboof** [comment]
Of course! The main change is that this unseals `CommentCreator` so users can provide their own. 

Additionally, it adds a `existingText: Option[String]` parameter to `CommentCreator.apply`, so that you can optionally take into account the existing header text.

This can be used to make sure the copyright year is preserved. I can provide a crude regex-based implementation of that as a unit test, though doing it 'really correctly' might be hard so I'm not proposing adding such an implementation to the plugin itself just yet :).

**Comment by hseeberger** [comment]
@raboof, thanks, LGTM.

@britter, what do you as the creator of commentcreator think?

**Comment by hseeberger** [comment]
Nice!

**Pull request merged**
