### PR TITLE
WIP: #60 - Twirl comment style

### PR DESCRIPTION
**Pull request by britter**
Fix for #60. Adds a new comment style which can bee activated like this:

```scala
headers := Map(
  "scala.html" -> Apache2_0("2015", "Heiko Seeberger", "@*")
)
```

It will add comment blocks of the form:

```
@***********
 * Comment *
 ***********@
```

This is currently WIP, since the failing scripted test shows, that it doesn't work currently. It looks like the collection of files passed to the `createHeaders` task does not contain the `index.scala.html` file. I suspect that this is a problem with the file collections defined in `toBeScopedSettings` but I don't know how to fix this. @hseeberger any idea?

### CODE REVIEW

**Comment by britter** [comment]
This seems to be related to #26

**Comment by hseeberger** [comment]
Well, also with #26 one would have to configure the `unmanagedSourceDirectories` to include the directory holding the templates. I'm not a Play-er, but I guess making the project used for the test a Play-project should do the job.

**Comment by hseeberger** [comment]
OK, screw the previous. I haven't seen that you put the template file under the Scala sources.

But here's the core issue:
```
scala> val extensionPattern = """.+\.(.+)""".r // As in `package.scala`
extensionPattern: scala.util.matching.Regex = .+\.(.+)

scala> val extensionPattern(ext) = "Hello.scala"
ext: String = scala

scala> val extensionPattern(ext) = "index.scala.html"
ext: String = html```

So the above extension pattern treats the last segment as the extension whereas in your test you use "scala.html".

**Comment by britter** [comment]
@hseeberger I've created an integration test with a real play project (generated with activator).

The headers are still not created for Twirl templates. This is because they are not part of `unamangedSources` or `unmanagedResources`. Looking at the SbtTwirl plugin, which is imported by the Play plugin, I understand that the template directory is defined via the [`compileTemplates`](https://github.com/playframework/twirl/blob/master/sbt-twirl/src/main/scala/play/twirl/sbt/SbtTwirl.scala#L21) setting. So I think I have to add the value of this setting to `createHeaders`. In the play-twirl test project in test.sbt I tried:

```scala
import play.twirl.sbt.Import.TwirlKeys

unmanagedSources in createHeaders ++= (TwirlKey.compileTemplates in Compile).value
```

But this fails with:

```
[error] Reference to undefined setting:
[error]
[error]   *:createHeaders::unmanagedSources from *:createHeaders::unmanagedSources (/Users/bene/workspace/misc/sbt-header/src/sbt-test/sbt-header/play-twirl/test.sbt:8)
[error]      Did you mean compile:createHeaders::unmanagedSources ?
```

So I somehow have to tell is to use those unmanagedSources which are used by createHeaders in compile and add the compileTemplates to that collection. But I don't know how.

**Comment by britter** [comment]
Found a way to include Twirl templates. This has to go to the user build:

```scala
unmanagedSources.in(Compile, createHeaders) ++= sources.in(Compile, TwirlKeys.compileTemplates)
```

I still have problems with the comment detection. Further more the requestor asked us to support both block comments as well as simple multiline comments. I need to implement that as well.

**Comment by britter** [comment]
Opening a new PR for this.

**Pull request closed without merging**
