### PR TITLE
Fix #105

### LINKED ISSUE #105: Source files are sometimes read and written with differing charsets
sbt-header reads source files with the system's default charset and writes them with UTF-8.
If there is a mismatch between the two sbt-header messes up the files original encoding.

### PR DESCRIPTION
**Pull request by sirthias**
Fixes #105.

### CODE REVIEW

**Comment by sirthias** [comment]
The failing check ("no non-ANSI characters allowed") doesn't really apply to a test that is explicitly testing UTF-8 encoding behavior.

**Comment by britter** [comment]
> The failing check ("no non-ANSI characters allowed") doesn't really apply to a test that is explicitly testing UTF-8 encoding behavior.

**Comment by britter** [comment]
Thank you for the PR, I'll have a look later today!

**Comment by sirthias** [comment]
We cannot guess the encoding and SBT doesn't know the encoding either (as it is defined in a combination of env vars and the compiler settings).
But I've never seen anyone intentionally using something other than UTF-8 in the field, so I think simply *requiring* all source files to be UTF-8 encoded and treating them accordingly is the simple and best thing for us to do here.

The important thing is to never accidentally use the system default charset, which is all too easy unfortunately.

**Comment by britter** [comment]
Agreed, this definitely makes the situation better. So we should apply this.

**Pull request merged**
